### ISSUE TITLE
Rails: prefer JSON endpoints

### ISSUE THREAD

**Issue by wuz** [lessonly/lessonly.github.io#104]
I would like to propose that we start moving towards a more [JAMstack](https://jamstack.org/)/[Immutable Web App](https://immutablewebapps.org/) style of building the application. With that in mind, I think establishing a rule around whether or not we pass data through ERB or load data via an JSON endpoint. Basically, instead of:

```ruby
<%= react_component("TestComponent", props: {
    data: SomeSerializer.new(@data).as_json,
  }) %>
```

```js
import React, { Component } from 'react';

class TestComponent extends Component {
	render() {
		const { data } = this.props;
		return <Something data={data} />
	}
}

```

we would just render the React component and in that component we would do a fetch/request:

```ruby
<%= react_component("TestComponent") %>
```

```js
import React, { Component } from 'react';

class TestComponent extends Component {
	constructor(props) {
		super(props);
		this.state = { 
			loading: true,
			data: {},
		}
	}
	componentDidMount() {
		request('/someserialized/data.json').then((data) => {
			this.setState({ data, loading: false });
		});
	}
	render() {
		const { data } = this.state;
		return <Something data={data}/>
	}
}

```

Arguments in favor:

- This would allow us at some point to split the React rendering into a separate SPA, which could be served from S3 and heavily cached.
- This allows Rails to handle just rendering data, without having to deal with ERB's or marked up views.
- This is very much the "new style" of building applications (which could be good or bad, but I would argue is good)

I'd love to hear others thoughts!

**Comment by stevegrossi** [comment]
I'm 100% on board with "ERB is dead [at Lessonly]", since that seems to be the direction we're heading anyway. The JAMstack stuff (seems more like an approach than a stack to me since there's so much flexibility in _how_ you do it) seems in line with how we prefer to do things today.

As for your examples, that's [exactly the approach we took with Insights](https://github.com/lessonly/lessonly/blob/master/doc/insights.md#asynchronous-loading) and so far I think it's worked out great. A formulation of this standard might be something like:

> Avoid ERB views and server-rendered markup when possible. Instead, we prefer to mount React components that fetch the data they need to render themselves via JSON endpoints.

**Comment by armilam** [comment]
I am fully on board with this idea. I look forward to a future where our Rails app is 100% API and the client side is 100% React.

**Comment by wernull** [comment]
I like this as well. It makes dealing with performance/scaling issues a lot easier and allows us to handle the errors/timeouts more gracefully on the front end. No one likes the big red X.

**Comment by joshmfrankel** [comment]
I'm in favor as well. I like separating the concerns up between ERB and JSX

**Comment by stevegrossi** [comment]
Sounds like we have a lot of agreement! I'd love to see this in the Style Guide itself. @wuz would you like to open the PR? I'm willing to otherwise.

**Comment by wsmd** [comment]
I'm fully on board too!

That's in fact an approach that a loft of parts in the app take as well: the Learn Dashboard, AssignModal, PathViewer (learner facing paths) and Workspaces are good examples to follow this.

I think we're at a point where we should be very conformable taking this approach. 

> This allows Rails to handle just rendering data, without having to deal with ERB's or marked up views.

Unfortunately, rails would still have to handle routing and basic rendering of ERB files to get react_on_rails handle the rest.[ The Learn dashboard](https://github.com/lessonly/lessonly/blob/master/client/assets/javascripts/components/Learn/Content/index.jsx#L19-L24) is the only page in the app currently to disobey this rule after initial render ;)

I can still see us relying on passing additional initial props such as features flags, etc for the time being (until we have a better way of doing this).

```erb
<%= react_component("TestComponent", props: {
  features: {
    feature_x: current_company.has_feature("feature_x")
  }
}) %>
```

**Comment by wuz** [comment]
> Unfortunately, rails would still have to handle routing and basic rendering of ERB files to get react_on_rails handle the rest. The Learn dashboard is the only page in the app currently to disobey this rule after initial render ;)

Yeah, I think the ultimate goal would be to separate them, but we definitely can't do that right now. The ERB's would have to stick around, but if they are just there for the purpose of rendering the React component and not passing data I think that works well. It makes it really easy to separate them later.
