### ISSUE TITLE
Document our use of the policy pattern and pundit

### ISSUE THREAD

**Issue by stevegrossi** [lessonly/lessonly.github.io#67]
https://github.com/elabs/pundit

**Comment by stevegrossi** [comment]
- Policy scopes are responsible for answering "What records should a user even know exist?"
- Policy predicate methods assume the user can know about the record, and are responsible for answering "Can this user take some action on a record?"

For example, a common pattern in controllers is to find a record through a policy scope and then `authorize` a particular action on it:

```ruby
def show
  @lesson = policy_scope(Lesson).find(params[:id])
  authorize @lesson # implicitly checks the show? predicate method because it's the current action
end
```

This way, the `LessonPolicy#show?` predicate method doesn't need to check that the lesson belongs to the same company as the user: we can assume that's already been done.

**Comment by stevegrossi** [comment]
We should include plenty of examples (do policies need their own style guide page?), like how to dynamically instantiate polymorphic policies:

```ruby
# app/controllers/taggings_controller.rb
def create
  taggable = policy_scope!(params[:taggable_type].safe_constantize).find(params[:taggable_id])
end
```

Should we whitelist `taggable_type` in this case? Probably, but how?

**Comment by stevegrossi** [comment]
> For example, a common pattern in controllers is to find a record through a policy scope and then authorize a particular action on it

[We don't want to do this anymore, Steve!](https://lessonly.slack.com/files/U048AJQRZ/F7L9DGW8G/Untitled.rb)

```ruby
# Instead of this (how we usually do things)
def update
  # checks whether you can know the lesson exists:
  @lesson = policy_scope(Lesson).find(params[:id])
  # checks whether your role lets you update it:
  authorize @lesson
end

# We propose this instead
def update
  @lesson = Lesson.find(params[:id])
  # checks whether you can know the Lesson exists
  # *and* that your role has permission to update @lesson
  authorize @lesson
end
```

**Comment by stevegrossi** [comment]
@baldwindavid [started thinking](https://github.com/lessonly/lessonly/pull/4414#discussion_r155058226) about what the best convention for calling policy scopes *within* policies (when needed) would be:

```ruby
def update?
  Scope.new(user, Tag).include?(record)
end
```

I like that, though I would add that it could be a bit more concise thanks to a shortcut in `PolicyHelpers`:

```ruby
def update?
  policy_scope!(Tag).include?(record)
end
```

and potentially even shorter with new code, though perhaps at the cost of clarity:

```ruby
def update?
  in_scope?(record)
end

# ApplicationPolicy
def in_scope?(record)
  policy_scope!(user, record.class).include?(record)
end
```

**Comment by baldwindavid** [comment]
One issue is that the `include?` route would be okay for persisted records, but not for new. I was kind of hoping to reuse the scope within the specific methods, but maybe another option is...

```ruby
def new?
  record.company == company && user.admin
```

`company` is available to us via `PolicyHelpers`

We could also add something like `record_in_same_company` to `PolicyHelper` if it helps.

**Comment by stevegrossi** [comment]
Good point! I do think it'd be worthwhile to have our policies work for both persisted and unpersisted records. For instance, I think it'd be useful to authorize new records in the create action:

```ruby
def create
  @tagging = Tagging.new(tagging_params)
  authorize @tagging # makes sure tagging_params point to authorized associations
end
```

**Comment by baldwindavid** [comment]
One thing to note here is that the controller `authorize` method returns the object being authorized on the master branch. However, the latest gem version of 1.1.0 (which we are on) returns `true`. This allows doing things like...

```ruby
@tag = authorize Tag.find(params[:id])
```

as opposed to...

```ruby
@tag = Tag.find(params[:id])
authorize @tag
```

I rather like the behavior of returning the object, but not sure we want to run off of master. Perhaps we could target a specific commit if we really want that behavior though. Or we could probably override it.

**Comment by stevegrossi** [comment]
> I rather like the behavior of returning the object, but not sure we want to run off of master.

I'd be fine with running off master (I think `Gemfile.lock` will lock in the latest commit when we run the initial `bundle update pundit`). Our policies are among the most thoroughly-tested objects in our codebase, so I'd feel confident that we're okay if they continue to pass.

**Comment by baldwindavid** [comment]
> I think Gemfile.lock will lock in the latest commit when we run the initial bundle update pundit

Well, thanks bundler!

**Comment by stevegrossi** [comment]
More discussion: https://lessonly.slack.com/archives/C047M50C0/p1510071148000508

**Comment by joshmfrankel** [comment]
Undocumented namespace examples: https://github.com/varvet/pundit/pull/392/files

**Comment by joshmfrankel** [comment]
I briefly started a Pull Request for this: https://github.com/lessonly/lessonly.github.io/pull/92

**Comment by joshmfrankel** [comment]
Since we have a styleguide entry for Policies and Pundit should we go ahead and close this issue?

**Comment by stevegrossi** [comment]
Heck yeah! 🕺
